#!/bin/bash

# Check if the case_name is passed as an argument
if [ -z "$1" ]; then
    echo "Usage: $0 <case_name>"
    exit 1
fi

case_name=$1
case_file="testcase/$case_name.txt"
if [ ! -f $case_file ]; then 
    echo "Error: Required files '$case_file' is missing in the folder."
    exit 1
fi

if [ ! -f "Lab1" ]; then
    echo "Error: Required files 'Lab1' is missing in the folder."
    exit 1
fi



timeout 60 ./Lab1 testcase/"${case_name}.txt" "output.txt" "${case_name}.txt"
